language: ruby
cache: bundler
sudo: false
rvm:
- 2.4

before_script: bundle update
script: bundle exec ruby script/stackprof

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
