language: ruby
cache: bundler
rvm:
  - 2.6

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document

before_script:
  - bundle update

script: bundle exec ruby script/memprof

branches:
  only:
  - master
  - memory_profiler

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
